require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/addto_books", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AddtoBook. As you add validations to AddtoBook, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AddtoBook.create! valid_attributes
      get addto_books_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      addto_book = AddtoBook.create! valid_attributes
      get addto_book_url(addto_book)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_addto_book_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      addto_book = AddtoBook.create! valid_attributes
      get edit_addto_book_url(addto_book)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AddtoBook" do
        expect {
          post addto_books_url, params: { addto_book: valid_attributes }
        }.to change(AddtoBook, :count).by(1)
      end

      it "redirects to the created addto_book" do
        post addto_books_url, params: { addto_book: valid_attributes }
        expect(response).to redirect_to(addto_book_url(AddtoBook.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AddtoBook" do
        expect {
          post addto_books_url, params: { addto_book: invalid_attributes }
        }.to change(AddtoBook, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post addto_books_url, params: { addto_book: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested addto_book" do
        addto_book = AddtoBook.create! valid_attributes
        patch addto_book_url(addto_book), params: { addto_book: new_attributes }
        addto_book.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the addto_book" do
        addto_book = AddtoBook.create! valid_attributes
        patch addto_book_url(addto_book), params: { addto_book: new_attributes }
        addto_book.reload
        expect(response).to redirect_to(addto_book_url(addto_book))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        addto_book = AddtoBook.create! valid_attributes
        patch addto_book_url(addto_book), params: { addto_book: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested addto_book" do
      addto_book = AddtoBook.create! valid_attributes
      expect {
        delete addto_book_url(addto_book)
      }.to change(AddtoBook, :count).by(-1)
    end

    it "redirects to the addto_books list" do
      addto_book = AddtoBook.create! valid_attributes
      delete addto_book_url(addto_book)
      expect(response).to redirect_to(addto_books_url)
    end
  end
end
