 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users_books", type: :request do
  
  # UsersBook. As you add validations to UsersBook, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      UsersBook.create! valid_attributes
      get users_books_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      users_book = UsersBook.create! valid_attributes
      get users_book_url(users_book)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_users_book_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      users_book = UsersBook.create! valid_attributes
      get edit_users_book_url(users_book)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UsersBook" do
        expect {
          post users_books_url, params: { users_book: valid_attributes }
        }.to change(UsersBook, :count).by(1)
      end

      it "redirects to the created users_book" do
        post users_books_url, params: { users_book: valid_attributes }
        expect(response).to redirect_to(users_book_url(UsersBook.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UsersBook" do
        expect {
          post users_books_url, params: { users_book: invalid_attributes }
        }.to change(UsersBook, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post users_books_url, params: { users_book: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested users_book" do
        users_book = UsersBook.create! valid_attributes
        patch users_book_url(users_book), params: { users_book: new_attributes }
        users_book.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the users_book" do
        users_book = UsersBook.create! valid_attributes
        patch users_book_url(users_book), params: { users_book: new_attributes }
        users_book.reload
        expect(response).to redirect_to(users_book_url(users_book))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        users_book = UsersBook.create! valid_attributes
        patch users_book_url(users_book), params: { users_book: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested users_book" do
      users_book = UsersBook.create! valid_attributes
      expect {
        delete users_book_url(users_book)
      }.to change(UsersBook, :count).by(-1)
    end

    it "redirects to the users_books list" do
      users_book = UsersBook.create! valid_attributes
      delete users_book_url(users_book)
      expect(response).to redirect_to(users_books_url)
    end
  end
end
